<a href="https://colab.research.google.com/github/smayan-kumar-panda/capGcodes/blob/main/NumpyCapG.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Basics


In [ ]:
import numpy as np
var1=np.array((1,2,3,'smayan'))

var1

array(['1', '2', '3', 'smayan'], dtype='<U21')

In [ ]:
var1.dtype  # data type

dtype('<U21')

In [ ]:
type(var1)

numpy.ndarray

In [ ]:
# upcasting

var2=np.array((1,2,3.1,2+6j,'smayan'))
var2

# everything is converted inside the array
# numpy array will not throw error if multiple datatypes is thrown but it upcasts the datatype

# order of upcasting --> bool--> int--> float--> complex--> str--> set--> dict

s=np.array(['smaya','huishia','busbvu'])
type(s)
s

array(['smaya', 'huishia', 'busbvu'], dtype='<U7')

In [ ]:
# vectorization (performing arithmetioc operations on arrays)

arr1=np.array([1,2,3,4,5])

arr1+1
arr1-1
arr1*2
arr1/2
arr1%2
arr1//2
arr1**2

array([ 1,  4,  9, 16, 25])

In [ ]:
# broadcasting (length of array should of of same size or if one dimension) --> adding arrays, the shape of arrays should be same for performing broadcasting


a1=np.array([1,2,3])
a2=np.array([5,6,7])
a1+a2
a1-a2

array([-4, -4, -4])

In [ ]:
# properties

dt=np.array([1,2,3.5])
dt.dtype

## dtype is used to check the overall datatype of the array
## even if the diffrent elements of the array are if diffrent data types upcasting converts them into single data type

dt.size  # no of elements

3

In [ ]:
dt.shape


(3,)

In [ ]:
dt.ndim  # tells the no. of dimensions

marr1=np.array([[
                [1,2,3],
                [4,5,6],
                [7,8,9]
                ],

               [
                [1,2,3],
                [4,5,6],
                [7,8,9]
                ]])


marr1.ndim  # 3
marr1.shape #(2, 3, 3)
marr1.dtype
marr1.size  # no of elements


18

In [ ]:
marr2=np.array([[[
                [1,2,3],
                [4,5,6],
                [7,8,9]
                ],

               [
                [1,2,3],
                [4,5,6],
                [7,8,9]
                ]],[[
                [1,2,3],
                [4,5,6],
                [7,8,9]
                ],

               [
                [1,2,3],
                [4,5,6],
                [7,8,9]
                ]]])

marr2.size  # 36
marr2.shape  # 2,2,3,3
marr2.ndim  # 4
#marr2

4

In [ ]:
# indexing in array (n dimensional array)

di1=np.array( [[[1,2,3],[4,5,6],[7,8,9]] , [[1,2,3],[4,5,6],[7,8,9]]] )

di1[1]
di1[-1]

di1[1][2][0]  # or di1[1,2,0]

np.int64(7)

In [ ]:
di1
marr1

di1+marr1+marr2  # broadcasting goes from right to left

array([[[[ 3,  6,  9],
         [12, 15, 18],
         [21, 24, 27]],

        [[ 3,  6,  9],
         [12, 15, 18],
         [21, 24, 27]]],


       [[[ 3,  6,  9],
         [12, 15, 18],
         [21, 24, 27]],

        [[ 3,  6,  9],
         [12, 15, 18],
         [21, 24, 27]]]])

In [ ]:
arr2=np.array([[1,2,3],[4,5,6]])
arr2.shape

marr1.shape
marr1+arr2



ValueError: operands could not be broadcast together with shapes (2,3,3) (2,3) 

In [ ]:
# slicing

l=[1,2,3,4]
l[1:3:1]
l[1:3]
l[1::2]

abc=np.array([1,2,3,4,5])
abc

abc[::-1]  # reversing the array
abc[::-1][1:3:1]  # slicing after reversing

In [ ]:
# slicing in 2d array

def1=np.array([[1,2,3],
              [4,5,6]])
def1[0][1:3]
def1[:,2]  # taking the 3rd column from the 3rd column

def1[0:3,2]
def1[:,1:3]  # before , rows and after , columns



In [ ]:
marr1[:,:,2]   # for 3d array

marr1[1:,1:,:]

marr1[1][1:,2:]

### IMP Functions in numpy

In [ ]:
# aarange

range(10)
range(1,10,2)

np.arange(1,10,3.5)

# arange accepts floating point step values


In [ ]:
ar=np.array(np.arange(1,11,0.5))
ar

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5])

In [ ]:
ar1=np.array(np.arange(0,6))
ar1

array([0, 1, 2, 3, 4, 5])

In [ ]:
import numpy as np
zeroes=np.array(np.zeros((3,3)))
zeroes

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.zeros((2,3,4))  # takes the shape of the array as input

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
np.zeros(1)
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.full((3,2),-5)

array([[-5, -5],
       [-5, -5],
       [-5, -5]])

In [ ]:
np.full((10,5),100)

array([[100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100]])

In [ ]:
np.linspace(2,3,20)   # linear space

array([2.        , 2.05263158, 2.10526316, 2.15789474, 2.21052632,
       2.26315789, 2.31578947, 2.36842105, 2.42105263, 2.47368421,
       2.52631579, 2.57894737, 2.63157895, 2.68421053, 2.73684211,
       2.78947368, 2.84210526, 2.89473684, 2.94736842, 3.        ])

In [ ]:
np.linspace(1,10)  # default is 50 values in each range if spacing not specified

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.random.rand(3,3)

np.random.randint(3,10,(3,4))

array([[6, 3, 8, 6],
       [7, 9, 7, 6],
       [4, 8, 9, 6]])

# Statistical Function

In [ ]:
# mean,median, mode, variance, std deviation, avg

np.mean(di1)
np.sum(di1)
np.var(di1)
np.std(di1)

np.median(di1)
np.average(di1)
np.empty((3,3))   # stores garbage value

t=np.array([1,2,3,4,5,6,7,8,9,10])
t.reshape((5,2))
marr1.reshape(-1)

NameError: name 'np' is not defined